---
# Master playbook to run database and application provisioning playbooks
- name: Install Nginx playbook
  import_playbook: install_nginx.yaml

- name: Install MongoDB
  import_playbook: install_mongodb.yaml

- name: Run database provisioning playbook
  import_playbook: prov-db.yaml

- name: Run application provisioning playbook
  import_playbook: prov_app_with_npm_start.yaml
