---
# MongoDB configuration playbook
- name: Configure MongoDB database
  hosts: db
  gather_facts: yes
  become: true

  tasks:
    - name: Update bind IP to allow remote connections
      ansible.builtin.lineinfile:
        path: "/etc/mongod.conf"
        search_string: '127.0.0.1'
        line: "  bindIp: 0.0.0.0"
        state: present

    - name: Ensure MongoDB is enabled and started
      ansible.builtin.service:
        name: mongod
        enabled: yes
        state: started

# Node.js application provisioning playbook
- name: Provision Node.js application
  hosts: web
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install NodeSource Node.js 20.x repository
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Clone the application repository to the controller node
      delegate_to: localhost
      ansible.builtin.git:
        repo: 'https://github.com/IlhaanHasssan/tech264-sparta-app.git'
        dest: /home/ubuntu/repo
        version: main

    - name: Copy app folder to target node
      ansible.builtin.copy:
        src: /home/ubuntu/repo/
        dest: /home/ubuntu/repo/
        mode: '0755'

    - name: Install npm packages based on package.json
      community.general.npm:
        path: /home/ubuntu/repo/app/

    - name: Start the application using pm2
      ansible.builtin.shell: |
        pm2 start app.js
      args:
        chdir: /home/ubuntu/repo/app/
